import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { Provider } from "react-redux";
import "../data/";
import BlankLayout from "../src/layouts/BlankLayout";
import FullLayout from "../src/layouts/FullLayout";
import { store } from "../store/Store";
import "../styles/style.scss";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
const layouts = {
  Blank: BlankLayout,
};
const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLIC_API_KEY);
// console.log({
//   key1: process.env.NEXT_PUBLIC_STRIPE_SECRET_API_KEY,
//   key2: process.env.NEXT_PUBLIC_STRIPE_PUBLIC_API_KEY,
// });

function MyApp({ Component, pageProps }) {
  const Layout = layouts[Component.layout] || FullLayout;
  return (
    <Provider store={store}>
      <Head>
        <title>Everyday AI Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Elements stripe={stripePromise}>
        <SessionProvider session={pageProps.session}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </SessionProvider>
      </Elements>
    </Provider>
  );
}

export default MyApp;
